name: Reviewed and tested

on:
    pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  trigger-ci:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Invoke workflow
      uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Unit testing
          token: ${{ secrets.WORKFLOW_RUN }}
          ref: ${{ github.event.pull_request.head.ref }}
